fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    registration:
        form:
            type: FOS\UserBundle\Form\Type\ProfileFormType
            #handler: cyclear_game.user_form.handler.registration
    from_email:
        address:        noreply@cyclear.nl
        sender_name:    Cyclear

    service:
        mailer: App\Mailer\FOSUserBundleMailer
