fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    registration:
        form:
            type: admin_user_new
            #handler: cyclear_game.user_form.handler.registration
    from_email:
        address:        noreply@cyclear.nl
        sender_name:    Cyclear

    service:
        mailer: 'fos_user.mailer.noop'