cyclear_api_renner:
    type:     rest
    resource: Cyclear\GameBundle\Controller\API\RiderController
    prefix: /api
cyclear_api_seizoen:
    type:     rest
    resource: Cyclear\GameBundle\Controller\API\SeasonController
    prefix: /api
cyclear_api_ploeg:
    type:     rest
    parent: cyclear_api_seizoen
    resource: Cyclear\GameBundle\Controller\API\TeamController