imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    version: 2.0.0
    cq_ranking-wedstrijdurl: 'http://cqranking.com/men/asp/gen/race.asp?raceid='

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: %version%

    translator:      { fallback: en_GB }
    default_locale: %locale%
    session:
      save_path: ~ 

# Twig Configuration
twig:
    globals:
      version: %version%
      logging_address: %logging_address%
      corresponding_address: %corresponding_address%
    debug:            %kernel.debug%
    strict_variables: true
    form:
      resources:
        - 'CyclearGameBundle:Form:rennerSelector.html.twig'
        - 'bootstrap_3_layout.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        # %kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.min.js
    assets:
            fonts_glyphicons_eot:
                inputs:
                   - "%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.eot"
                output: "fonts/glyphicons-halflings-regular.eot"
            fonts_glyphicons_svg:
                inputs:
                    - "%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.svg"
                output: "fonts/glyphicons-halflings-regular.svg"
            fonts_glyphicons_ttf:
                inputs:
                    - "%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.ttf"
                output: "fonts/glyphicons-halflings-regular.ttf"
            fonts_glyphicons_woff:
                inputs:
                    - "%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.woff"
                output: "fonts/glyphicons-halflings-regular.woff"
            fonts_glyphicons_woff2:
                inputs:
                    - "%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.woff2"
                output: "fonts/glyphicons-halflings-regular.woff2"
# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
          gedmo_translatable:
            type: annotation
            prefix: Gedmo\Translatable\Entity
            dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
            alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
            is_bundle: false
        dql:
          string_functions:
            ifnull: DoctrineExtensions\Query\Mysql\IfNull
            if: DoctrineExtensions\Query\Mysql\IfElse
            date: DoctrineExtensions\Query\Mysql\Date
            date_format: DoctrineExtensions\Query\Mysql\DateFormat
    
cyclear_game:
  enable_twitter: true
  max_transfers: %max_transfers%

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_all_services: false

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Cyclear\GameBundle\Entity\User
    registration:
      form:
        type: admin_user_new
        #handler: cyclear_game.user_form.handler.registration
    from_email:
        address:        noreply@cyclear.nl
        sender_name:    Cyclear

stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default: 
          sluggable: true
          translatable: true

mobile_detect:
    redirect:
        mobile: ~
        tablet: ~
    switch_device_view: ~

knp_paginator:
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig