parameters:
    database_driver: pdo_mysql
    database_host: ~
    database_port: ~
    database_name: ~
    database_user: ~
    database_password: ~

    mailer_transport: smtp
    mailer_host: localhost
    mailer_user :
    mailer_password :

    locale: nl_NL

    secret: Make_a_new_one
    
    twitter_consumer_key: ~
    twitter_consumer_secret: ~
    twitter_oauth_token: ~
    twitter_oauth_secret: ~
