# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
_welcome:
    pattern:  /
    defaults: { _controller: CyclearGameBundle:Default:index }

CyclearGameBundle:
    resource: "@CyclearGameBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /login-user/

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /game/{seizoen}/

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /admin/user/new

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /reset-password/

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /game/{seizoen}/

fos_user_security_check:
    prefix: /
    pattern: /login_check
    
fos_user_security_logout:
    prefix: /
    pattern: /logout

fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"