security:
    encoders:
        Cyclear\GameBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10
    
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login-user/login
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path:  /login-user/login
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login-user/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/user, role: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
    acl:
      connection:  default