security:
    encoders:
        Cyclear\GameBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10
    
    providers:
        main:
            entity: { class: CyclearGameBundle:User, property: username }
        fos_userbundle:
            id: fos_user.user_provider.username
    
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path:  /login-user/login
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login-user/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/user, role: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
    acl:
      connection:  default