# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

index:
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::indexAction' }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /login-user/

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /game/{seizoen}/

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /admin/user/new

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /reset-password/

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /game/{seizoen}/

fos_user_security_check:
    prefix: /
    path: /login_check

fos_user_security_logout:
    prefix: /
    path: /logout

_welcome:
    path: /

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
