<?php

/*
 * This file is part of the Cyclear-game package.
 *
 * (c) Erik Trapman <veggatron@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cyclear\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;
use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * RennerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RennerRepository extends EntityRepository
{

    public function findOneByNaam($naam)
    {
        return $this->findOneBy(array('naam' => $naam));
    }

    /**
     * @param $id
     * @return null|object|Renner
     */
    public function findOneByCQId($id)
    {
        return $this->findOneBy(array('cqranking_id' => $id));
    }

    public function findOneBySelectorString($rennerString)
    {
        $firstBracket = strpos($rennerString, '[');
        $lastBracket = strpos($rennerString, ']');
        $cqId = trim(substr($rennerString, 0, $firstBracket));
        $name = substr($rennerString, $firstBracket + 1, $lastBracket - $firstBracket - 1);

        return $this->findOneBy(array('naam' => $name, 'cqranking_id' => $cqId));
    }

    public function getPloeg($renner, $seizoen = null)
    {
        if (null === $seizoen) {
            $seizoen = $this->_em->getRepository("CyclearGameBundle:Seizoen")->getCurrent();
        }
        if (is_numeric($renner)) {
            $renner = $this->_em->getRepository("CyclearGameBundle:Renner")->find($renner);
        }
        $contract = $this->_em->getRepository("CyclearGameBundle:Contract")->getCurrentContract($renner, $seizoen);
        if (null === $contract) {
            return null;
        }
        return $contract->getPloeg();
    }

    /**
     * @param Renner $renner
     * @param Ploeg $ploeg
     * @return bool
     */
    public function isDraftTransfer(Renner $renner, Ploeg $ploeg)
    {
        return (bool)$this->_em->getRepository(Transfer::class)->hasDraftTransfer($renner, $ploeg);
    }

    public function getRennersWithPloeg($seizoen = null)
    {
        if (null === $seizoen) {
            $seizoen = $this->_em->getRepository("CyclearGameBundle:Seizoen")->getCurrent();
        }
        $rennersWithPloeg = array();
        foreach ($this->_em->getRepository("CyclearGameBundle:Contract")
                     ->createQueryBuilder('c')
                     ->where('c.seizoen = :seizoen')
                     ->andWhere('c.eind IS NULL')->setParameter('seizoen', $seizoen)
                     ->getQuery()->getResult() as $contract) {
            $rennersWithPloeg [] = $contract->getRenner();
        }
        return $rennersWithPloeg;
    }

    /**
     * @param null $seizoen
     * @param bool $excludeWithTeam
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getRennersWithPunten($seizoen = null, $excludeWithTeam = false)
    {
        if (null === $seizoen) {
            $seizoen = $this->_em->getRepository("CyclearGameBundle:Seizoen")->getCurrent();
        }
        $puntenQb = $this->_em->getRepository('CyclearGameBundle:Uitslag')
            ->createQueryBuilder('u')
            ->select('SUM(u.rennerPunten)')
            ->innerJoin('u.wedstrijd', 'w')
            ->where('u.renner = r')
            ->andWhere('w.seizoen = :seizoen')//    ->setParameter('seizoen', $seizoen)
        ;
        $teamQb = $this->_em->getRepository('CyclearGameBundle:Contract')
            ->createQueryBuilder('c')
            ->select('p.afkorting')
            ->innerJoin('c.ploeg', 'p')
            ->where('c.seizoen = :seizoen')
            ->andWhere('c.eind IS NULL')
            ->andWhere('c.renner = r')//->setParameter('seizoen', $seizoen)
        ;
        $qb = $this->createQueryBuilder('r')
            ->addSelect('IFNULL((' . $puntenQb->getDQL() . '), 0) AS punten', 'IFNULL((' . $teamQb->getDQL() . '), -1) AS team')
            ->leftJoin('r.country', 'cty')->addSelect('cty')
            ->orderBy('punten', 'DESC, r.naam ASC');
        if (true === $excludeWithTeam) {
            $qb->having("team < 0");
        }
        return $qb->setParameter('seizoen', $seizoen); //->setMaxResults(20)->getQuery()->getResult();
    }

}